CREATE DATABASE CONEXIA;
USE CONEXIA;

CREATE TABLE CLIENTE(
  ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
  NOMBRE_CLIENTE VARCHAR(30),
  APELLIDO_PATERNO_CLIENTE VARCHAR(30),
  APELLIDO_MATERNO_CLIENTE VARCHAR(30),
  OBSERVACIONES TEXT,
  PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE MESA(
  ID_MESA INT NOT NULL AUTO_INCREMENT,
  NUMERO_MAX_COMENSAL INT,
  UBICACION TEXT,
  PRIMARY KEY(ID_MESA)
);

CREATE TABLE COCINERO(
  ID_COCINERO INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(30),
  APELLIDO_PATERNO_CLIENTE VARCHAR(30),
  APELLIDO_MATERNO_COCINERO VARCHAR(30),
  PRIMARY KEY(ID_COCINERO)
);

CREATE TABLE CAMARERO(
  ID_CAMARERO INT NOT NULL AUTO_INCREMENT,
  NOMBRE_CAMARERO VARCHAR(30),
  APELLIDO_PATERNO_CAMARERO VARCHAR(30),
  APELLIDO_MATERNO_CAMARERO VARCHAR(30),
  PRIMARY KEY(ID_CAMARERO)
);

CREATE TABLE FACTURA(
  ID_FACTURA INT NOT NULL AUTO_INCREMENT,
  ID_CLIENTE INT NOT NULL,
  ID_CAMARERO INT NOT NULL,
  ID_MESA INT NOT NULL,
  FECHA_FACTURA DATE,
  PRIMARY KEY(ID_FACTURA),
  FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  FOREIGN KEY(ID_CAMARERO) REFERENCES CAMARERO(ID_CAMARERO),
  FOREIGN KEY(ID_MESA) REFERENCES MESA(ID_MESA)
);

CREATE TABLE DETALLE_FACTURA(
  ID_DETALLE INT NOT NULL AUTO_INCREMENT,
  ID_FACTURA INT NOT NULL,
  ID_COCINERO INT NOT NULL,
  PRIMARY KEY(ID_DETALLE),
  FOREIGN KEY(ID_FACTURA) REFERENCES FACTURA(ID_FACTURA),
  FOREIGN KEY(ID_COCINERO) REFERENCES COCINERO(ID_COCINERO)
);


CREATE TABLE CONEXIA.PLATO (
	ID_PLATO INT NOT NULL AUTO_INCREMENT,
	NOMBRE_PLATO varchar(30) NULL,
	VALOR_PLATO BIGINT UNSIGNED NULL,
	PRIMARY KEY (ID_PLATO)
)

INSERT INTO CONEXIA.CAMARERO (NOMBRE_CAMARERO,APELLIDO_PATERNO_CAMARERO,APELLIDO_MATERNO_CAMARERO) VALUES
('Jeisson','Barrero','Molina')
;

INSERT INTO CONEXIA.CLIENTE (NOMBRE_CLIENTE,APELLIDO_PATERNO_CLIENTE,APELLIDO_MATERNO_CLIENTE,OBSERVACIONES) VALUES
('Nathaly','Salamanca','Rativa','Mala paga')
;

INSERT INTO CONEXIA.PLATO (NOMBRE_PLATO,VALOR_PLATO,DETALLE_PLATO) VALUES
('spaghetti',5000,'Plato de pasta sin adereso')
,('baby beef',10000,'Corte de carne')
,('hamburguesa',12000,'Hamburguesa')
,('Papas fritas',5000,'Papas en fosforo fritas')
;

INSERT INTO CONEXIA.MESA (NUMERO_MAX_COMENSAL,UBICACION) VALUES
(5,'CENTRO')
;
